// Example

const resourceNum = {
  name: "Resource Name",
  link: "/assets/subject-number.pdf",
  description: "Explains blah blah blah",
};

// List of resources below.

// On experience addition, make a new JavaScript object as above.
// Add resourceNum to FRONT of english_res or spanish_res for it to be visible.
// You can crtl + f to find them ^

// psst don't forget the comma after every attribute ;)

const resource15 = {
  name: "How to Solve the Arnold Conjecture (Slides)",
  link: "/assets/english/floer-1.pdf",
  description: "Slides for my presentation at the 2026 MIT DRP Symposium. In this talk, I presented the Arnold conjecture and outlined how to solve the problem using the techniques of Floer homology.",
};

const resource14 = {
  name: "Factoriales!",
  link: "/assets/spanish/teoria-numeros-4.pdf",
  description: "",
};

const resource13 = {
  name: "Ecuaciones Diof&aacutenticas",
  link: "/assets/spanish/teoria-numeros-3.pdf",
  description: "",
};

const resource12 = {
  name: "Divisibilidad",
  link: "/assets/spanish/teoria-numeros-2.pdf",
  description: "",
};

const resource11 = {
  name: "Aritm&eacutetica Modular",
  link: "/assets/spanish/teoria-numeros-1.pdf",
  description: "",
};

const resource10 = {
  name: "Transformaciones",
  link: "/assets/spanish/geometria-4.pdf",
  description: "",
};

const resource9 = {
  name: "Semejanza y Cuadril&aacuteteros C&iacuteclicos",
  link: "/assets/spanish/geometria-3.pdf",
  description: "",
};

const resource8 = {
  name: "Homotecia y el C&iacuterculo de los Nueve Puntos",
  link: "/assets/spanish/geometria-2.pdf",
  description: "",
};

const resource7 = {
  name: "Coordenadas Cartesianas y Rect&aacutengulos",
  link: "/assets/spanish/geometria-1.pdf",
  description: "",
};

const resource6 = {
  name: "La Desigualdad del Reacomodo",
  link: "/assets/spanish/algebra-1.pdf",
  description: "",
};

const resource5 = {
  name: "Representations to get Braid Invariants (Lecture Notes)",
  link: "/assets/english/knot-theory-4.pdf",
  description: "Lecture notes for my final talk for MIT's Seminar in Topology (18.904). In this talk, I presented braids and the braid group, and showed how to use representations of the braid group to obtain a braid invariant known as the writhe.",
};

const resource4 = {
  name: "Using Dehn Surgery to Calculate Homology (Lecture Notes)",
  link: "/assets/english/knot-theory-3.pdf",
  description: "Lecture notes for my third talk for MIT's Seminar in Topology (18.904). In this talk, I used Dehn surgeries to compute the homologies of certain cyclic covers of knot complements.",
};

const resource3 = {
  name: "Dehn Twists Generate the Mapping Class Group (Lecture Notes)",
  link: "/assets/english/knot-theory-2.pdf",
  description: "Lecture notes for my second talk for MIT's Seminar in Topology (18.904). In this talk, I proved that the Mapping Class Group of any compact orientable surface is generated by Dehn Twists.",
};

const resource2 = {
  name: "Additivity of Genus (Lecture Notes)",
  link: "/assets/english/knot-theory-1.pdf",
  description: "Lecture notes for my first talk for MIT's Seminar in Topology (18.904). In this talk, I proved that knot genus is additive.",
};

const resource1 = {
  name: "Introduction to Combinatorics (Lecture Notes)",
  link: "/assets/english/combinatorics-1.pdf",
  description: "These lecture notes were created for the Summer 2025 edition of the <a href='https://edu.stacyvazquez.com/programs'>Stem Advancement Program by Stacy</a>, where I served as the teaching assistant.",
};

// Add HERE

const english_res = [resource15, resource2, resource3, resource4, resource5, resource1];
const spanish_res = [
  resource6,
  resource7,
  resource8,
  resource9,
  resource10,
  resource11,
  resource12,
  resource13,
  resource14,
];
